postinst: added useful stuff from postinst.ex template

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,13 +1,30 @@
 #!/bin/sh
+# postinst script for android-permissions
+#
+# see: dh_installdeb(1)
 
 set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 
 usergroupadd() {
 	grep -q ^$2: /etc/group || groupadd -r -g $1 $2
 	grep -q ^$2: /etc/passwd || useradd -r -g $1 -u $1 -d /system $2
 }
 
-case $1 in configure)
+case "$1" in
+    configure)
 	# Add UID/GID values statically defined in Bionic Libc
 	usergroupadd 1000 system       # system server
 	usergroupadd 1001 radio        # telephony subsystem, RIL
@@ -55,6 +72,20 @@ case $1 in configure)
 		s/^[[:space:]]*#\?[[:space:]]*\(ADD_EXTRA_GROUPS[[:space:]]*=[[:space:]]*\)[[:digit:]]\+/\11/
 		s/^[[:space:]]*#\?[[:space:]]*\(EXTRA_GROUPS[[:space:]]*=[[:space:]]*\).*/\1"shell graphics input log adb sdcard_rw net_bt_admin net_bt inet"/
 	' /etc/adduser.conf
-;;esac
+        ;;
+    
+    abort-upgrade|abort-remove|abort-deconfigure)
+        ;;
+    
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+        ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
 
 exit 0
